apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: kiran
  annotations:
    kubernetes.io/change-cause: "deployment for nginx from Argocd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: c1
        image: nginxdemos/hello
        ports:
        - containerPort: 80
      - name: c2
        image: kiran2275/demo-nginx:4
        ports:
        - containerPort: 8080
