apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: kiran
  annotations:
    kubernetes.io/change-cause: "service for nginx from Argocd"
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80